
// This file has been generated by the GUI designer. Do not modify.
namespace test5.Widgets
{
	public partial class WindowDevice
	{
		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget test5.Widgets.WindowDevice
			this.Name = "test5.Widgets.WindowDevice";
			this.Title = global::Mono.Unix.Catalog.GetString("WindowDevice");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
